name: medimg
channels:
  - defaults
  - nvidia
  - pytorch
dependencies:
  - anyio=4.10.0=py311haa95532_0
  - argon2-cffi=25.1.0=py311haa95532_0
  - argon2-cffi-bindings=25.1.0=py311h02ab6af_0
  - asttokens=3.0.0=py311haa95532_0
  - async-lru=2.0.5=py311haa95532_0
  - attrs=25.4.0=py311haa95532_2
  - babel=2.17.0=py311haa95532_0
  - beautifulsoup4=4.14.2=py311haa95532_0
  - blas=1.0=mkl
  - bleach=6.3.0=py311haa95532_0
  - brotlicffi=1.2.0.0=py311h885b0b7_0
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - certifi=2025.11.12=py311haa95532_0
  - cffi=2.0.0=py311h02ab6af_1
  - charset-normalizer=3.4.4=py311haa95532_0
  - colorama=0.4.6=py311haa95532_0
  - comm=0.2.3=py311haa95532_0
  - cuda-cccl=12.9.27=0
  - cuda-cccl_win-64=12.9.27=0
  - cuda-cudart=12.1.105=0
  - cuda-cudart-dev=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-libraries-dev=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvrtc-dev=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.9.19=0
  - cuda-opencl-dev=12.9.19=0
  - cuda-profiler-api=12.9.79=0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.9=3
  - debugpy=1.8.16=py311h885b0b7_1
  - decorator=5.2.1=py311haa95532_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - executing=2.2.1=py311haa95532_0
  - expat=2.7.3=h885b0b7_4
  - filelock=3.20.0=py311haa95532_0
  - freetype=2.13.3=h0620614_0
  - giflib=5.2.2=h7edc060_0
  - gmp=6.3.0=h537511b_0
  - gmpy2=2.2.2=py311h8598115_0
  - h11=0.16.0=py311haa95532_1
  - html5lib=1.1=pyhd3eb1b0_0
  - httpcore=1.0.9=py311haa95532_0
  - httpx=0.28.1=py311haa95532_1
  - idna=3.11=py311haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - ipykernel=6.31.0=py311h4442805_0
  - ipython=9.7.0=py311haa95532_0
  - ipython_pygments_lexers=1.1.1=py311haa95532_0
  - jedi=0.19.2=py311haa95532_0
  - jinja2=3.1.6=py311haa95532_0
  - jpeg=9f=ha349fce_0
  - json5=0.12.1=py311haa95532_0
  - jsonschema=4.25.0=py311haa95532_1
  - jsonschema-specifications=2025.9.1=py311haa95532_0
  - jupyter-lsp=2.2.5=py311haa95532_0
  - jupyter_client=8.6.3=py311haa95532_1
  - jupyter_core=5.9.1=py311haa95532_0
  - jupyter_events=0.12.0=py311haa95532_1
  - jupyter_server=2.17.0=py311haa95532_0
  - jupyter_server_terminals=0.5.3=py311haa95532_0
  - jupyterlab=4.5.0=py311haa95532_0
  - jupyterlab_pygments=0.3.0=py311haa95532_0
  - jupyterlab_server=2.28.0=py311haa95532_0
  - khronos-opencl-icd-loader=2025.07.22=h79b28c9_0
  - lcms2=2.16=hb4a4139_0
  - lerc=3.0=hd77b12b_0
  - libcublas=12.1.0.26=0
  - libcublas-dev=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufft-dev=11.0.2.4=0
  - libcurand=10.3.10.19=0
  - libcurand-dev=10.3.10.19=0
  - libcusolver=11.4.4.55=0
  - libcusolver-dev=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libcusparse-dev=12.0.2.55=0
  - libdeflate=1.17=h2bbff1b_1
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libjpeg-turbo=2.0.0=h196d8e1_0
  - libnpp=12.0.2.50=0
  - libnpp-dev=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjitlink-dev=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libnvjpeg-dev=12.1.1.14=0
  - libpng=1.6.50=h46444df_0
  - libsodium=1.0.20=h83e8143_0
  - libtiff=4.5.1=hd77b12b_0
  - libuv=1.48.0=h827c3e9_0
  - libwebp=1.3.2=hbc33d0d_0
  - libwebp-base=1.3.2=h3d04722_1
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - markupsafe=3.0.2=py311h827c3e9_0
  - matplotlib-inline=0.2.1=py311haa95532_0
  - mistune=3.1.2=py311haa95532_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py311h827c3e9_2
  - mkl_fft=1.3.11=py311h827c3e9_0
  - mkl_random=1.2.8=py311hea22821_0
  - mpc=1.3.1=h827c3e9_0
  - mpfr=4.2.1=h56c3642_0
  - mpmath=1.3.0=py311haa95532_0
  - nbclient=0.10.2=py311haa95532_0
  - nbconvert-core=7.16.6=py311haa95532_0
  - nbformat=5.10.4=py311haa95532_0
  - nest-asyncio=1.6.0=py311haa95532_0
  - networkx=3.6.1=py311haa95532_0
  - notebook-shim=0.2.4=py311haa95532_0
  - opencl-headers=2025.07.22=h885b0b7_0
  - openjpeg=2.5.2=hae555c5_0
  - openssl=3.0.18=h543e019_0
  - overrides=7.7.0=py311haa95532_0
  - packaging=25.0=py311haa95532_1
  - pandocfilters=1.5.1=py311haa95532_0
  - parso=0.8.5=py311haa95532_0
  - pillow=11.1.0=py311h096bfcc_0
  - pip=25.3=pyhc872135_0
  - platformdirs=4.5.0=py311haa95532_0
  - prometheus_client=0.21.1=py311haa95532_0
  - prompt-toolkit=3.0.52=py311haa95532_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - psutil=7.0.0=py311h02ab6af_1
  - pure_eval=0.2.3=py311haa95532_0
  - pycparser=2.23=py311haa95532_0
  - pygments=2.19.2=py311haa95532_0
  - pysocks=1.7.1=py311haa95532_1
  - python=3.11.14=h981015d_0
  - python-dateutil=2.9.0post0=py311haa95532_2
  - python-fastjsonschema=2.21.2=py311haa95532_0
  - python-json-logger=4.0.0=py311haa95532_0
  - pytorch-cuda=12.1=hde6ce7c_6
  - pytorch-mutex=1.0=cuda
  - pywin32=311=py311h885b0b7_0
  - pywinpty=2.0.15=py311h72d21ff_0
  - pyyaml=6.0.3=py311hb9a58be_0
  - pyzmq=27.1.0=py311h7149c55_1
  - referencing=0.37.0=py311haa95532_0
  - requests=2.32.5=py311haa95532_1
  - rfc3339-validator=0.1.4=py311haa95532_0
  - rfc3986-validator=0.1.1=py311haa95532_0
  - rpds-py=0.28.0=py311h114bc41_0
  - send2trash=1.8.2=py311haa95532_1
  - setuptools=80.9.0=py311haa95532_0
  - six=1.17.0=py311haa95532_0
  - sniffio=1.3.1=py311haa95532_0
  - soupsieve=2.5=py311haa95532_0
  - sqlite=3.51.0=hda9a48d_0
  - stack_data=0.6.3=py311haa95532_0
  - tbb=2021.8.0=h59b6b97_0
  - terminado=0.18.1=py311haa95532_0
  - tinycss2=1.4.0=py311haa95532_0
  - tk=8.6.15=hf199647_0
  - tornado=6.5.4=py311h02ab6af_0
  - traitlets=5.14.3=py311haa95532_0
  - typing-extensions=4.15.0=py311haa95532_0
  - typing_extensions=4.15.0=py311haa95532_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wcwidth=0.2.13=py311haa95532_0
  - webencodings=0.5.1=py311haa95532_1
  - websocket-client=1.8.0=py311haa95532_0
  - wheel=0.45.1=py311haa95532_0
  - win_inet_pton=1.1.0=py311haa95532_1
  - winpty=0.4.3=4
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.5=h6c54ac7_1
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
  - pip:
      - absl-py==2.3.1
      - acvl-utils==0.2.5
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - albucore==0.0.24
      - albumentations==2.0.8
      - altair==6.0.0
      - annotated-types==0.7.0
      - argparse==1.4.0
      - asyncio-atexit==1.0.1
      - batchgenerators==0.25.1
      - batchgeneratorsv2==0.3.0
      - blinker==1.9.0
      - blosc2==4.0.0
      - cachetools==6.2.6
      - click==8.3.1
      - connected-components-3d==3.26.1
      - contourpy==1.3.3
      - cycler==0.12.1
      - datasets==4.4.2
      - deprecated==1.3.1
      - dill==0.4.0
      - dynamic-network-architectures==0.4.3
      - einops==0.8.2
      - et-xmlfile==2.0.0
      - fft-conv-pytorch==1.2.0
      - fonttools==4.61.1
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - future==1.0.0
      - gitdb==4.0.12
      - gitpython==3.1.46
      - googleapis-common-protos==1.72.0
      - graphviz==0.21
      - grpcio==1.76.0
      - hiddenlayer==0.3
      - huggingface-hub==0.36.0
      - imagecodecs==2026.1.14
      - imageio==2.37.2
      - importlib-metadata==8.7.1
      - importlib-resources==6.5.2
      - ipywidgets==8.1.8
      - joblib==1.5.3
      - jupyterlab-widgets==3.0.16
      - kagglehub==0.3.13
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - linecache2==1.0.0
      - lxml==6.0.2
      - markdown==3.10
      - matplotlib==3.10.8
      - monai==1.5.1
      - msgpack==1.1.2
      - multidict==6.7.0
      - multiprocess==0.70.18
      - narwhals==2.15.0
      - ndindex==1.10.1
      - nibabel==5.3.3
      - nnunetv2==2.6.3
      - numexpr==2.14.1
      - numpy==2.4.1
      - opencv-python==4.13.0.90
      - opencv-python-headless==4.13.0.90
      - openpyxl==3.1.5
      - opentelemetry-api==1.39.1
      - opentelemetry-exporter-otlp-proto-common==1.39.1
      - opentelemetry-exporter-otlp-proto-http==1.39.1
      - opentelemetry-instrumentation==0.60b1
      - opentelemetry-instrumentation-httpx==0.60b1
      - opentelemetry-instrumentation-requests==0.60b1
      - opentelemetry-instrumentation-threading==0.60b1
      - opentelemetry-instrumentation-urllib==0.60b1
      - opentelemetry-proto==1.39.1
      - opentelemetry-sdk==1.39.1
      - opentelemetry-semantic-conventions==0.60b1
      - opentelemetry-util-http==0.60b1
      - pandas==2.3.3
      - propcache==0.4.1
      - protobuf==6.33.2
      - pyarrow==22.0.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydeck==0.9.1
      - pydicom==3.0.1
      - pyparsing==3.3.1
      - python-docx==1.2.0
      - pytorch-ignite==0.5.3
      - pytz==2025.2
      - regex==2025.11.3
      - reportlab==4.4.9
      - safetensors==0.7.0
      - scikit-image==0.26.0
      - scikit-learn==1.8.0
      - scipy==1.16.3
      - seaborn==0.13.2
      - simpleitk==2.5.3
      - simsimd==6.5.12
      - smmap==5.0.2
      - streamlit==1.53.1
      - stringzilla==4.6.0
      - sympy==1.13.1
      - synapseclient==4.11.0
      - tenacity==9.1.2
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.6.0
      - tifffile==2026.1.28
      - timm==1.0.22
      - tokenizers==0.22.1
      - toml==0.10.2
      - torch==2.5.1+cu121
      - torchaudio==2.5.1+cu121
      - torchvision==0.20.1+cu121
      - tqdm==4.67.1
      - traceback2==1.4.0
      - transformers==4.57.3
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - unittest2==1.1.0
      - urllib3==2.6.3
      - watchdog==6.0.0
      - werkzeug==3.1.4
      - widgetsnbextension==4.0.15
      - wrapt==1.17.3
      - xxhash==3.6.0
      - yacs==0.1.8
      - yarl==1.22.0
      - zipp==3.23.0
prefix: C:\Users\hyeon\miniconda3\envs\medimg
